/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as SearchRouteImport } from './routes/search'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as YardRouteImport } from './routes/yard'
import { Route as ListingSkuRouteImport } from './routes/listing.$sku'
import { Route as LotLotRouteImport } from './routes/lot.$lot'
import { Route as MarketItemIdRouteImport } from './routes/market.$itemId'
import { Route as PartOemRouteImport } from './routes/part.$oem'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as VinVinRouteImport } from './routes/vin.$vin'
import { Route as VinVinAssemblyRouteImport } from './routes/vin.$vin.$assembly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const YardRoute = YardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingSkuRoute = ListingSkuRouteImport.update({
  id: '/listing/$sku',
  path: '/listing/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const LotLotRoute = LotLotRouteImport.update({
  id: '/lot/$lot',
  path: '/lot/$lot',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketItemIdRoute = MarketItemIdRouteImport.update({
  id: '/market/$itemId',
  path: '/market/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartOemRoute = PartOemRouteImport.update({
  id: '/part/$oem',
  path: '/part/$oem',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VinVinRoute = VinVinRouteImport.update({
  id: '/vin/$vin',
  path: '/vin/$vin',
  getParentRoute: () => rootRouteImport,
} as any)
const VinVinAssemblyRoute = VinVinAssemblyRouteImport.update({
  id: '/$assembly',
  path: '/$assembly',
  getParentRoute: () => VinVinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/vehicles': typeof VehiclesRoute
  '/yard': typeof YardRoute
  '/listing/$sku': typeof ListingSkuRoute
  '/lot/$lot': typeof LotLotRoute
  '/market/$itemId': typeof MarketItemIdRoute
  '/part/$oem': typeof PartOemRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/vin/$vin': typeof VinVinRouteWithChildren
  '/vin/$vin/$assembly': typeof VinVinAssemblyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/vehicles': typeof VehiclesRoute
  '/yard': typeof YardRoute
  '/listing/$sku': typeof ListingSkuRoute
  '/lot/$lot': typeof LotLotRoute
  '/market/$itemId': typeof MarketItemIdRoute
  '/part/$oem': typeof PartOemRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/vin/$vin': typeof VinVinRouteWithChildren
  '/vin/$vin/$assembly': typeof VinVinAssemblyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sale': typeof SaleRoute
  '/search': typeof SearchRoute
  '/vehicles': typeof VehiclesRoute
  '/yard': typeof YardRoute
  '/listing/$sku': typeof ListingSkuRoute
  '/lot/$lot': typeof LotLotRoute
  '/market/$itemId': typeof MarketItemIdRoute
  '/part/$oem': typeof PartOemRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/vin/$vin': typeof VinVinRouteWithChildren
  '/vin/$vin/$assembly': typeof VinVinAssemblyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sale'
    | '/search'
    | '/vehicles'
    | '/yard'
    | '/listing/$sku'
    | '/lot/$lot'
    | '/market/$itemId'
    | '/part/$oem'
    | '/vehicle/$id'
    | '/vin/$vin'
    | '/vin/$vin/$assembly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sale'
    | '/search'
    | '/vehicles'
    | '/yard'
    | '/listing/$sku'
    | '/lot/$lot'
    | '/market/$itemId'
    | '/part/$oem'
    | '/vehicle/$id'
    | '/vin/$vin'
    | '/vin/$vin/$assembly'
  id:
    | '__root__'
    | '/'
    | '/sale'
    | '/search'
    | '/vehicles'
    | '/yard'
    | '/listing/$sku'
    | '/lot/$lot'
    | '/market/$itemId'
    | '/part/$oem'
    | '/vehicle/$id'
    | '/vin/$vin'
    | '/vin/$vin/$assembly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SaleRoute: typeof SaleRoute
  SearchRoute: typeof SearchRoute
  VehiclesRoute: typeof VehiclesRoute
  YardRoute: typeof YardRoute
  ListingSkuRoute: typeof ListingSkuRoute
  LotLotRoute: typeof LotLotRoute
  MarketItemIdRoute: typeof MarketItemIdRoute
  PartOemRoute: typeof PartOemRoute
  VehicleIdRoute: typeof VehicleIdRoute
  VinVinRoute: typeof VinVinRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yard': {
      id: '/yard'
      path: '/yard'
      fullPath: '/yard'
      preLoaderRoute: typeof YardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$sku': {
      id: '/listing/$sku'
      path: '/listing/$sku'
      fullPath: '/listing/$sku'
      preLoaderRoute: typeof ListingSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot/$lot': {
      id: '/lot/$lot'
      path: '/lot/$lot'
      fullPath: '/lot/$lot'
      preLoaderRoute: typeof LotLotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$itemId': {
      id: '/market/$itemId'
      path: '/market/$itemId'
      fullPath: '/market/$itemId'
      preLoaderRoute: typeof MarketItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part/$oem': {
      id: '/part/$oem'
      path: '/part/$oem'
      fullPath: '/part/$oem'
      preLoaderRoute: typeof PartOemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vin/$vin': {
      id: '/vin/$vin'
      path: '/vin/$vin'
      fullPath: '/vin/$vin'
      preLoaderRoute: typeof VinVinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vin/$vin/$assembly': {
      id: '/vin/$vin/$assembly'
      path: '/$assembly'
      fullPath: '/vin/$vin/$assembly'
      preLoaderRoute: typeof VinVinAssemblyRouteImport
      parentRoute: typeof VinVinRoute
    }
  }
}

interface VinVinRouteChildren {
  VinVinAssemblyRoute: typeof VinVinAssemblyRoute
}

const VinVinRouteChildren: VinVinRouteChildren = {
  VinVinAssemblyRoute: VinVinAssemblyRoute,
}

const VinVinRouteWithChildren =
  VinVinRoute._addFileChildren(VinVinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SaleRoute: SaleRoute,
  SearchRoute: SearchRoute,
  VehiclesRoute: VehiclesRoute,
  YardRoute: YardRoute,
  ListingSkuRoute: ListingSkuRoute,
  LotLotRoute: LotLotRoute,
  MarketItemIdRoute: MarketItemIdRoute,
  PartOemRoute: PartOemRoute,
  VehicleIdRoute: VehicleIdRoute,
  VinVinRoute: VinVinRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
