# Sample workflow for building and deploying a static site to GitHub Pages
name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: ["main"] # Deploys when changes are pushed to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub Actions tab

permissions:
  contents: read # Allows the workflow to read the repository content
  pages: write # Allows the workflow to deploy to GitHub Pages
  id-token: write # Required for OpenID Connect (OIDC) authentication with GitHub Pages

concurrency:
  group: "pages" # Ensures only one deployment runs at a time for this group
  cancel-in-progress: false # Prevents new runs from cancelling existing ones

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the runner environment
    steps:
      - name: Checkout # Checks out your repository code
        uses: actions/checkout@v4

      - name: Setup Pages # Configures GitHub Pages environment
        uses: actions/configure-pages@v5

      - name: Upload artifact # Uploads your site files as an artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # Point to the directory containing your static files.
          # For a single index.html and an images folder in the root,
          # '.' means the entire repository root will be uploaded.
          path: './' 

  deploy:
    environment:
      name: github-pages # Specifies the deployment environment
      url: ${{ steps.deployment.outputs.page_url }} # The URL of the deployed site
    runs-on: ubuntu-latest # Specifies the runner environment
    needs: build # Ensures the build job completes successfully before deployment
    steps:
      - name: Deploy to GitHub Pages # Deploys the uploaded artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
